name: Codacy Security Scan

on:
  push:
    branches: 
      - "master"
      - "main"
  pull_request:
    branches: 
      - "master"
      - "main"

jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4 # Updated to a valid version
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 100

      - name: Upload Sarif Results File
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
