name: Vulnerability Scan
on: [push, pull_request]
jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@2
  - uses: debricked/actions/scan@v1
  env:
    DEBRICKED_TOKEN: ${{secrets.DEBRICKED_TOKEN}}
